SERVER-49333 use host.create for powercycle

diff --git a/etc/evergreen.yml b/etc/evergreen.yml
--- a/etc/evergreen.yml
+++ b/etc/evergreen.yml
@@ -2579,47 +2579,51 @@ functions:
         done
 
   "set up EC2 instance": &set_up_ec2_instance
+    - command: host.create
+      params:
+        provider: ec2
+        distro: ${distro_id}
+        key_name: ${key_name}
+        security_group_ids:
+        - sg-097bff6dd0d1d31d0
+
+    - command: host.list
+      params:
+        wait: true
+        timeout_seconds: 3000
+        num_hosts: 1
+        path: src/hosts.yml
+
     - command: shell.exec
       params:
-        working_dir: src
         script: |
+          user=${admin_user_name}
+          hostname=$(tr -d '"[]{}' < src/hosts.yml | cut -d , -f 1 | awk -F : '{print $2}')
+          identity_file=~/.ssh/mcipacker.pem
 
-          set -o errexit
-          ${activate_virtualenv}
+          # compat with old aws_ec2.yml file
+          echo "private_ip_address: $hostname" >> src/${aws_ec2_yml}
 
-          if [ ! -z "${subnet_id}" ]; then
-            subnet_id="-n ${subnet_id}"
-          fi
+          attempts=0
+          connection_attempts=${connection_attempts|25}
 
-          for security_group_id in ${security_group_ids}
+          # Check for remote connectivity
+          while ! ssh \
+            -i "$identity_file" \
+            -o ConnectTimeout=10 \
+            -o ForwardAgent=yes \
+            -o IdentitiesOnly=yes \
+            -o StrictHostKeyChecking=no \
+            "$(printf "%s@%s" "$user" "$hostname")" \
+            exit 2> /dev/null
           do
-            security_group_ids="$security_group_ids -g $security_group_id"
+            [ "$attempts" -ge "$connection_attempts" ] && exit 1
+            ((attempts++))
+            printf "SSH connection attempt %d/%d failed. Retrying...\n" "$attempts" "$connection_attempts"
+            # sleep for Permission denied (publickey) errors
+            sleep 10
           done
-
-          if [ -z "${security_group_ids}" ]; then
-            for security_group in ${security_groups}
-            do
-              security_groups="$security_groups -s $security_group"
-            done
-          fi
-
-          if [ -n "${ec2_expire_hours}" ]; then
-            expire_hours="-e ${ec2_expire_hours}"
-            # Since Windows hosts are expensive to keep running we'll expire it after 3 hours.
-            if [ "Windows_NT" = "$OS" ]; then
-              expire_hours="-e 3"
-            fi
-          fi
-
-          # Clone another instance of this host in EC2.
-          buildscripts/launch_evergreen_ec2_instance.sh \
-            $expire_hours                               \
-            -k ${ssh_key_id}                            \
-            $security_groups                            \
-            $security_group_ids                         \
-            $subnet_id                                  \
-            -t "AMI Evergreen ${task_id}"               \
-            -y ${aws_ec2_yml}
+        shell: bash
 
     - command: expansions.update
       params:
